### ISSUE TITLE
Error occurs when trying to run this mod in a server

### ISSUE THREAD

**Issue by mbakgor** [mim1q/ConvenientDecor#14]
Hey everyone, 

When I try to run this mod in server creation i get this error ; 

`[main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'convenientdecor'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-launcher.jar:1.0.1]
Caused by: java.lang.ExceptionInInitializerError
	at com.github.mim1q.convenientdecor.ConvenientDecor.onInitialize(ConvenientDecor.java:19) ~[convenientdecor-0.3.0.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 7 more
Caused by: java.lang.IllegalArgumentException: Block{minecraft:air} has property: type with invalidly named value: straıght
	at net.minecraft.state.StateManager$Builder.validate(StateManager.java:147) ~[server-intermediary.jar:?]
	at net.minecraft.state.StateManager$Builder.add(StateManager.java:127) ~[server-intermediary.jar:?]
	at com.github.mim1q.convenientdecor.block.PitchforkBlock.appendProperties(PitchforkBlock.java:32) ~[convenientdecor-0.3.0.jar:?]
	at net.minecraft.block.Block.<init>(Block.java:181) ~[server-intermediary.jar:?]
	at com.github.mim1q.convenientdecor.block.PitchforkBlock.<init>(PitchforkBlock.java:25) ~[convenientdecor-0.3.0.jar:?]
	at com.github.mim1q.convenientdecor.init.ModBlocks.<clinit>(ModBlocks.java:30) ~[convenientdecor-0.3.0.jar:?]
	at com.github.mim1q.convenientdecor.ConvenientDecor.onInitialize(ConvenientDecor.java:19) ~[convenientdecor-0.3.0.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 7 more
`

Is this line wrong? 

_Block{minecraft:air} has property: type with invalidly named value: straıght_

Can anyone help me?

**Comment by mim1q** [comment]
Please check if this update fixes the issue: https://modrinth.com/mod/convenient-decor/version/0.4.2

**Comment by mim1q** [comment]
Fixed, the same bug was happening in #15
